# Not a .NET project. We build it in the install script
build: false

#image:
  #- Visual Studio 2015

branches:
  only:
    - master
    - appveyor_conda
    - windows-deploy

platform:
  - x64

environment:
  MINICONDA: C:\Miniconda3
  QPALM_VERSION: "1.0"

install:
  - "%APPVEYOR_BUILD_FOLDER%\\appveyor\\install.cmd"

test_script:
  - "%APPVEYOR_BUILD_FOLDER%\\appveyor\\script.cmd"


deploy_script:
  - "%APPVEYOR_BUILD_FOLDER%\\ci\\appveyor\\deploy.cmd"


