# Not a .NET project. We build it in the install script
build: false

image:
  - Visual Studio 2015

branches:
  only:
    - master
    - appveyor_conda

platform:
  - x64
  #- x86

environment:
  MINICONDA: C:\Miniconda3
  #CMAKE_PROJECT: MinGW Makefiles

init:

  # Uncomment for remote desktop debug
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#  - ECHO %PYTHON_VERSION% %MINICONDA%

install:
  - call %MINICONDA%\Scripts\activate.bat
  #- cmd: IF NOT EXIST C:\cache\OpenBLAS appveyor DownloadFile https://sjeng.org/ftp/OpenBLAS-0.3.3-win-oldthread.zip
  #- cmd: IF NOT EXIST C:\cache\OpenBLAS 7z x OpenBLAS-0.3.3-win-oldthread.zip -oC:\cache\OpenBLAS
  - "%APPVEYOR_BUILD_FOLDER%\\appveyor\\install.cmd"

test_script:
  - "%APPVEYOR_BUILD_FOLDER%\\appveyor\\script.cmd"

#deploy_script:
#  - "%APPVEYOR_BUILD_FOLDER%\\ci\\appveyor\\deploy.cmd"


