# Not a .NET project. We build it in the install script
build: false

#image:
  #- Visual Studio 2015

branches:
  only:
    - none

platform:
  - x64

environment:
  MINICONDA: C:\Miniconda3
  QPALM_VERSION: "2.0"

install:
  - "%APPVEYOR_BUILD_FOLDER%\\appveyor\\install.cmd"

test_script:
  - "%APPVEYOR_BUILD_FOLDER%\\appveyor\\script.cmd"

deploy_script:
  - IF "%APPVEYOR_REPO_BRANCH%"=="master" ("%APPVEYOR_BUILD_FOLDER%\\appveyor\\deploy.cmd")


